### ISSUE TITLE
journals are blank in Monk's Enhanced Journal

### ISSUE THREAD

**Issue by sharkbruhaha** [pchouzenoux/foundryvtt-dnd5-cheatsheet#10] opened 2021-07-19 05:43 UTC
No idea why, but when using Monk's Enhanced Journal, all the entries are blank:
![image](https://user-images.githubusercontent.com/44031572/126108674-56df907e-4ab8-4e63-a616-a010f699fd6a.png)

**Comment by pchouzenoux** [comment] 2021-07-20 00:02
Hi,

I tested and I'm not able to reproduce this issue, I tested with versions:
- FoundryVTT: `0.8.8`
- Dnd5 Cheatsheet: `0.0.6`
- Monk's Enhanced Journal: `1.0.17`

Can you tell me which version are you using ? May you can update your version to see if it fix the issue ?

**Comment by pchouzenoux** [comment] 2021-09-14 01:01
I close this issue because I have no answer.

**Closed as completed by pchouzenoux** 2021-09-14 01:01 UTC
Labels: bug
